
FLASK_NAME := k8s-flask

flask: flask/build/no_cache flask/push

# Build Docker image
flask/build:
	docker build -t $(FLASK_NAME) apps/flask

# Build Docker image without using cache
flask/build/no_cache:
	docker build --no-cache -t $(FLASK_NAME) apps/flask

# Push image to docker registry
flask/push:
	docker tag k8s-flask:latest localhost:5000/k8s-flask:latest
	docker push localhost:5000/k8s-flask:latest

# Ping API
flask/ping:
	seq 1 10000 | xargs -n 1 -P $$N_THREADS scripts/ping.sh

